CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(30) NOT NULL,
  "email" varchar(50) NOT NULL,
  "password" varchar(12) NOT NULL,
  "age" int NOT NULL,
  "rol_id_fk" int NOT NULL
);

CREATE TABLE "courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(30) NOT NULL,
  "description" varchar(100) NOT NULL,
  "level_id_fk" int NOT NULL,
  "teacher" varchar(30) NOT NULL,
  "course_videp_id_fk" int NOT NULL,
  "rol_id_fk" int NOT NULL
);

CREATE TABLE "course_videos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(30) NOT NULL,
  "url" varchar(100) NOT NULL
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(20) NOT NULL,
  "course_id_fk" int NOT NULL
);

CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(20) NOT NULL
);

CREATE TABLE "level" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(20) NOT NULL
)

ALTER TABLE "categories" ADD FOREIGN KEY ("course_id_fk") REFERENCES "courses" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("course_videp_id_fk") REFERENCES "course_videos" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("level_id_fk") REFERENCES "level" ("id");

ALTER TABLE "roles" ADD FOREIGN KEY ("id") REFERENCES "courses" ("rol_id_fk");

ALTER TABLE "roles" ADD FOREIGN KEY ("id") REFERENCES "users" ("rol_id_fk");

INSERT INTO roles (name) VALUES ('student'),('teacher'),('admin');

INSERT INTO level (name) VALUES ('principiantes'),('medios'), ('avanzados');

INSERT INTO course_videos (title, url) VALUES ('Nodejs para principiantes', 'www.academlo/nodejs.com'), ('React para principiantes', 'www.academlo/react.com');

INSERT INTO courses (title, description, level_id_fk, teacher, course_videp_id_fk, rol_id_fk) VALUES ('Nodejs' , 'Backend', 1, 'Ian', 1, 2 ), ('React', 'Frontend', 1, 'Andres', 2 , 2);

INSERT INTO categories (name, course_id_fk) VALUES ('Nodejs', 1), ('React', 2);

INSERT INTO users (name, email, password, age, rol_id_fk) VALUES ('Christian Rodriguez', 'chris@gmail.com', 'abcd1234', 29 , 1), ('Daniela Portilla', 'daniela@gmail.com', 'qwerty12', 29, 1);